from typing import TypedDict, List
from langchain_core.documents import Document

class GraphState(TypedDict):
    """
    Represents the state of the SELF-RAG graph.
    Every node will receive this dictionary and return updates to it.
    """
    # The original user question
    question: str 
    
    # The documents pulled by the retriever
    documents: List[Document] 
    
    # The current draft of the answer generated by the LLM
    generation: str 
    
    # A status flag used for routing (e.g., 'yes' or 'no')
    revision_needed: str